version: "3.7"


services:
    app:
        build:
            context: ./
        volumes:
            - ~/.ssh:/home/dmitriy/.ssh:rw
            - ./:/var/www
        depends_on:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "3307:3306"
            
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8080:80
        environment:
        - PMA_ARBITRARY=1

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/

    mailhog:
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
